"use client";

import { useEffect, useState } from "react";
import { api, ApiError } from "@/lib/api/client";
import type { Inclusion } from "@/lib/api/inclusions";

const categories=["kitchen","bathroom","electrical","flooring","facade","living","exterior","other"];
export default function AdminInclusionsPage(){
 const [items,setItems]=useState<Inclusion[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [file,setFile]=useState<File|null>(null); const [image,setImage]=useState<File|null>(null); const [title,setTitle]=useState(""); const [category,setCategory]=useState("kitchen"); const [features,setFeatures]=useState("");
 async function load(){setLoading(true);try{const data=await api.get<Inclusion[]|{results:Inclusion[]}>("/inclusions/?published=",{auth:true});setItems(Array.isArray(data)?data:data.results??[])}catch(e){setError(e instanceof ApiError?e.message:"Unable to load inclusions.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function add(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");try{const fd=new FormData();fd.append("title",title);fd.append("category",category);fd.append("features",JSON.stringify(features.split("\n").map(x=>x.trim()).filter(Boolean)));fd.append("published","true");fd.append("featured","false");if(file)fd.append("pdf",file);if(image)fd.append("image",image);const created=await api.post<Inclusion>("/inclusions/",fd,{auth:true});setItems(x=>[...x,created]);setTitle("");setFeatures("");setFile(null);setImage(null);const form=document.getElementById("inclusion-form") as HTMLFormElement|null;form?.reset();}catch(e){setError(e instanceof ApiError?e.message:"Unable to create inclusion.")}finally{setSaving(false)}}
 async function remove(slug:string){if(!confirm("Delete this inclusion?"))return;try{await api.delete(`/inclusions/${slug}/`,{auth:true});setItems(x=>x.filter(i=>i.slug!==slug))}catch(e){setError(e instanceof ApiError?e.message:"Delete failed.")}}
 return <div><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.35em] text-white/30">Content library</p><h1 className="mt-2 text-3xl font-light">Inclusions Library</h1><p className="mt-2 text-sm text-white/45">Upload a cover image and brochure PDF once; reuse the inclusion in your home and land content.</p></div></div>
 {error&&<div className="mt-6 rounded-xl border border-red-400/20 bg-red-400/10 px-4 py-3 text-sm text-red-200">{error}</div>}
 <form id="inclusion-form" onSubmit={add} className="mt-8 grid gap-4 rounded-2xl border border-white/10 bg-white/[.02] p-6 md:grid-cols-2"><div><label className="text-xs text-white/45">Title</label><input required value={title} onChange={e=>setTitle(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white" placeholder="Premium Kitchen Package"/></div><div><label className="text-xs text-white/45">Category</label><select value={category} onChange={e=>setCategory(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#111820] px-4 py-3 text-sm text-white">{categories.map(c=><option key={c} value={c}>{c}</option>)}</select></div><div><label className="text-xs text-white/45">Book cover image</label><input type="file" accept="image/*" onChange={e=>setImage(e.target.files?.[0]||null)} className="mt-2 w-full text-xs text-white/50"/></div><div><label className="text-xs text-white/45">Brochure PDF</label><input type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)} className="mt-2 w-full text-xs text-white/50"/></div><div className="md:col-span-2"><label className="text-xs text-white/45">Features, one per line</label><textarea value={features} onChange={e=>setFeatures(e.target.value)} className="mt-2 min-h-28 w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white"/></div><div className="md:col-span-2"><button disabled={saving} className="rounded-xl bg-[#8C1D2C] px-5 py-3 text-sm text-white disabled:opacity-50">{saving?'Publishing…':'Publish inclusion'}</button></div></form>
 <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{loading?<div className="text-sm text-white/40">Loading…</div>:items.map(item=><div key={item.id} className="rounded-2xl border border-white/10 bg-white/[.02] p-5"><div className="aspect-[1.3] overflow-hidden rounded-xl bg-white/5">{item.image_url&&<img src={item.image_url} alt="" className="h-full w-full object-cover"/>}</div><p className="mt-4 text-[9px] uppercase tracking-[.3em] text-white/35">{item.category}</p><h2 className="mt-1 text-lg text-white">{item.title}</h2><div className="mt-4 flex items-center justify-between"><span className="text-xs text-white/35">{item.pdf_url?'PDF ready':'No PDF'}</span><button onClick={()=>remove(item.slug)} className="text-xs text-red-300/70 hover:text-red-200">Delete</button></div></div>)}</div>
 </div>
}
