"use client";

import { useEffect, useState } from "react";
import { api, ApiError } from "@/lib/api/client";

type Client = { user_id:number; email:string; first_name:string; last_name:string; phone:string; is_client:boolean; is_reypro:boolean; assigned_agent:number|null; agent_name:string|null };
type Agent = { id:number; name:string; email:string };

export default function AdminClientsPage(){
  const [clients,setClients]=useState<Client[]>([]); const [agents,setAgents]=useState<Agent[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState<number|null>(null); const [error,setError]=useState("");
  useEffect(()=>{ Promise.all([api.get<Client[]>("/pro/admin/clients/",{auth:true}),api.get<Agent[]>("/pro/admin/agents/",{auth:true}).catch(()=>api.get<Agent[]>("/admin/agents/",{auth:true}))]).then(([c,a])=>{setClients(c);setAgents(a)}).catch(e=>setError(e?.message||"Unable to load clients.")).finally(()=>setLoading(false)); },[]);
  async function patch(user_id:number, body:Partial<Client>){setSaving(user_id);setError("");try{const next=await api.patch<Client>(`/pro/admin/clients/${user_id}/`,body,{auth:true});setClients(c=>c.map(x=>x.user_id===user_id?next:x));}catch(e){setError(e instanceof ApiError?e.message:"Save failed.")}finally{setSaving(null)}}
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.35em] text-white/30">Registered users & client management</p><h1 className="mt-2 text-3xl font-light">Users → Clients → ReyHomes Pro</h1><p className="mt-2 text-sm text-white/45">Every website registration starts as a normal user. Select a user as Client first; only Clients can receive ReyHomes Pro access.</p></div><div className="rounded-full border border-white/10 bg-white/[.03] px-4 py-2 text-xs text-white/50">{clients.filter(c=>c.is_reypro).length} Pro accounts</div></div>
    {error&&<div className="mt-6 rounded-xl border border-red-400/20 bg-red-400/10 px-4 py-3 text-sm text-red-200">{error}</div>}
    <div className="mt-8 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-white/10 bg-white/[.02] text-[10px] uppercase tracking-wider text-white/35"><tr><th className="px-5 py-4">Registered user</th><th className="px-5 py-4">Client status</th><th className="px-5 py-4">Agent</th><th className="px-5 py-4">ReyPro</th></tr></thead><tbody>{loading?<tr><td colSpan={4} className="px-5 py-10 text-center text-white/40">Loading clients…</td></tr>:clients.map(c=><tr key={c.user_id} className="border-b border-white/5 last:border-0"><td className="px-5 py-4"><div className="font-medium text-white">{c.first_name} {c.last_name}</div><div className="mt-1 text-xs text-white/40">{c.email}</div></td><td className="px-5 py-4"><button disabled={saving===c.user_id} onClick={()=>patch(c.user_id,{is_client:!c.is_client})} className={`rounded-full px-3 py-1.5 text-xs ${c.is_client?'bg-emerald-400/15 text-emerald-300':'bg-white/5 text-white/40'}`}>{c.is_client?'Client':'Normal user'}</button></td><td className="px-5 py-4"><select value={c.assigned_agent??""} onChange={e=>patch(c.user_id,{assigned_agent:e.target.value?Number(e.target.value):null})} className="rounded-xl border border-white/10 bg-[#111820] px-3 py-2 text-xs text-white"><option value="">Unassigned</option>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></td><td className="px-5 py-4"><button disabled={saving===c.user_id} onClick={()=>patch(c.user_id,{is_reypro:!c.is_reypro})} className={`rounded-full px-4 py-2 text-xs font-medium ${c.is_reypro?'bg-[#D8C7A4] text-[#0A1628]':'border border-white/10 bg-white/5 text-white/50'}`}>{c.is_reypro?'Enabled':'Enable Pro'}</button></td></tr>)}{!loading&&!clients.length&&<tr><td colSpan={4} className="px-5 py-10 text-center text-white/40">No member accounts yet.</td></tr>}</tbody></table></div>
    <div className="mt-7 rounded-2xl border border-white/10 bg-white/[.02] p-5 text-sm text-white/45">Tip: registration always creates a normal user. Promote the user to Client here after your business process/contract approval. Contract status never promotes a user automatically. ReyHomes Pro is a separate, deliberate admin permission and can only be enabled for Clients.</div>
  </div>
}
