# Generated by Django 5.2.17 on 2026-08-07 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, default='NSW', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='estates/')),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estate',
                'verbose_name_plural': 'Estates',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='land_estate_slug_303777_idx'), models.Index(fields=['published'], name='land_estate_publish_27fed8_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomeLandPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(choices=[('House & Land', 'House & Land'), ('Display Home', 'Display Home'), ('Land Only', 'Land Only')], default='House & Land', max_length=50)),
                ('state', models.CharField(blank=True, default='NSW', max_length=50)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('price_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(default=4)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=2, max_digits=3)),
                ('garage', models.PositiveSmallIntegerField(default=2)),
                ('land_size', models.CharField(blank=True, max_length=50)),
                ('house_size', models.CharField(blank=True, max_length=50)),
                ('frontage', models.CharField(blank=True, max_length=50)),
                ('depth', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='packages/hero/')),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to='packages/floorplans/')),
                ('badge', models.CharField(blank=True, help_text='Popular, New Release, etc.', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('inclusion_list', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='land.estate')),
            ],
            options={
                'verbose_name': 'Home & Land Package',
                'verbose_name_plural': 'Home & Land Packages',
                'ordering': ['-featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/features/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='land.homelandpackage')),
            ],
            options={
                'verbose_name': 'Package Feature',
                'verbose_name_plural': 'Package Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PackageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='land.homelandpackage')),
            ],
            options={
                'verbose_name': 'Package Gallery Image',
                'verbose_name_plural': 'Package Gallery Images',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='homelandpackage',
            index=models.Index(fields=['slug'], name='land_homela_slug_f9cd4e_idx'),
        ),
        migrations.AddIndex(
            model_name='homelandpackage',
            index=models.Index(fields=['published', 'featured'], name='land_homela_publish_bfd891_idx'),
        ),
        migrations.AddIndex(
            model_name='homelandpackage',
            index=models.Index(fields=['created_at'], name='land_homela_created_3bbfcb_idx'),
        ),
    ]
