# Generated by Django 5.2.17 on 2026-08-14 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inclusion_pdf'),
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelandpackage',
            name='inclusion_list',
            field=models.JSONField(blank=True, default=list, help_text='DEPRECATED: legacy inclusion strings. Use inclusions (via PackageInclusion). Kept read-only for one release cycle as a fallback.'),
        ),
        migrations.CreateModel(
            name='PackageInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('inclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_inclusion_links', to='core.inclusion')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusion_links', to='land.homelandpackage')),
            ],
            options={
                'verbose_name': 'Package Inclusion',
                'verbose_name_plural': 'Package Inclusions',
                'ordering': ['order'],
                'unique_together': {('package', 'inclusion')},
            },
        ),
        migrations.AddField(
            model_name='homelandpackage',
            name='inclusions',
            field=models.ManyToManyField(blank=True, related_name='package_links', through='land.PackageInclusion', to='core.inclusion'),
        ),
    ]
