# Generated by Django 5.2.17 on 2026-08-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, default='Explore', max_length=100)),
                ('button_link', models.CharField(blank=True, default='/home-designs', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='hero/mobile/')),
                ('video', models.FileField(blank=True, null=True, upload_to='hero/videos/')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='hero/posters/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ReyHomes', max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, help_text='e.g. Homeowner, Suburb NSW', max_length=150)),
                ('suburb', models.CharField(blank=True, max_length=150)),
                ('design', models.CharField(blank=True, help_text='Design or package name', max_length=150)),
                ('review', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('electrical', 'Electrical'), ('flooring', 'Flooring'), ('facade', 'Facade'), ('living', 'Living'), ('exterior', 'Exterior'), ('other', 'Other')], default='other', max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inclusions/')),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name or emoji', max_length=100)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature strings')),
                ('order', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inclusion',
                'verbose_name_plural': 'Inclusions',
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['slug'], name='core_inclus_slug_82b5b9_idx'), models.Index(fields=['published', 'featured'], name='core_inclus_publish_3130aa_idx')],
            },
        ),
    ]
