# Generated by Django 5.2.17 on 2026-08-07 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('Single Storey', 'Single Storey'), ('Double Storey', 'Double Storey'), ('Dual Occupancy', 'Dual Occupancy'), ('Knockdown Rebuild', 'Knockdown Rebuild')], default='Single Storey', max_length=50)),
                ('status', models.CharField(blank=True, help_text='Popular, New Release, etc.', max_length=50)),
                ('state', models.CharField(blank=True, default='NSW', max_length=50)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(help_text='Display price e.g. $435,000', max_length=50)),
                ('price_value', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric price for filtering/sorting', max_digits=12, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(default=4)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=2, max_digits=3)),
                ('garage', models.PositiveSmallIntegerField(default=2)),
                ('living', models.PositiveSmallIntegerField(default=1)),
                ('study', models.PositiveSmallIntegerField(default=0)),
                ('house_size', models.CharField(blank=True, max_length=50)),
                ('land_size', models.CharField(blank=True, max_length=50)),
                ('frontage', models.CharField(blank=True, max_length=50)),
                ('depth', models.CharField(blank=True, max_length=50)),
                ('min_lot_width', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='designs/hero/')),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to='designs/floorplans/')),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('related_slugs', models.JSONField(blank=True, default=list, help_text='List of related design slugs')),
                ('inclusion_list', models.JSONField(blank=True, default=list, help_text='Simple inclusion strings for this design')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Design',
                'verbose_name_plural': 'Home Designs',
                'ordering': ['-featured', 'title'],
                'indexes': [models.Index(fields=['slug'], name='homes_homed_slug_6570df_idx'), models.Index(fields=['published', 'featured'], name='homes_homed_publish_9c57c6_idx'), models.Index(fields=['category'], name='homes_homed_categor_51eaa8_idx'), models.Index(fields=['created_at'], name='homes_homed_created_222b68_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomeDesignFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='designs/features/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('home_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='homes.homedesign')),
            ],
            options={
                'verbose_name': 'Design Feature',
                'verbose_name_plural': 'Design Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeDesignGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='designs/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('home_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='homes.homedesign')),
            ],
            options={
                'verbose_name': 'Design Gallery Image',
                'verbose_name_plural': 'Design Gallery Images',
                'ordering': ['order'],
            },
        ),
    ]
