# Generated by Django 5.2.17 on 2026-08-14 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inclusion_pdf'),
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedesign',
            name='related_designs',
            field=models.ManyToManyField(blank=True, help_text='Real FK relations replacing related_slugs.', related_name='related_by', to='homes.homedesign'),
        ),
        migrations.AlterField(
            model_name='homedesign',
            name='inclusion_list',
            field=models.JSONField(blank=True, default=list, help_text='DEPRECATED: legacy inclusion strings. Use inclusions (via DesignInclusion). Kept read-only for one release cycle as a fallback.'),
        ),
        migrations.AlterField(
            model_name='homedesign',
            name='related_slugs',
            field=models.JSONField(blank=True, default=list, help_text='DEPRECATED: legacy list of related design slugs. Use related_designs. Kept read-only for one release cycle as a fallback.'),
        ),
        migrations.CreateModel(
            name='DesignInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('home_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusion_links', to='homes.homedesign')),
                ('inclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusion_links', to='core.inclusion')),
            ],
            options={
                'verbose_name': 'Design Inclusion',
                'verbose_name_plural': 'Design Inclusions',
                'ordering': ['order'],
                'unique_together': {('home_design', 'inclusion')},
            },
        ),
        migrations.AddField(
            model_name='homedesign',
            name='inclusions',
            field=models.ManyToManyField(blank=True, related_name='design_links', through='homes.DesignInclusion', to='core.inclusion'),
        ),
    ]
